server:
  port: 8082
  error:
    include-stacktrace: never
spring:
  application:
    name: hr-payroll
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

